# Generated by Django 4.2.28 on 2026-02-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_quiz_topic',
            field=models.CharField(blank=True, help_text='The topic string to use for the AI quiz generation for this course.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_final_quiz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='final_quiz_passed',
            field=models.BooleanField(default=False),
        ),
    ]
