# Generated by Django 4.2.28 on 2026-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
