# Generated by Django 4.2.28 on 2026-02-14 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0003_liveinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=100)),
                ('interview_type', models.CharField(max_length=100)),
                ('tech_stack', models.TextField()),
                ('num_questions', models.IntegerField(default=5)),
                ('vapi_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('communication_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('cultural_fit_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('detailed_feedback', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
